baseurl = "http://blog.songru.org/"
languageCode = "zh"
title = "Leon's Blog"
paginate = 10
[taxonomies]
  tag = "tags"
  category = "categories"
[indexes]
  tag = "tags"
  category = "categories"
[params]	#左侧边栏的标题和描述
    sidebartitle = "Leon's Blog"
    sidebartagline = "Is super awesome"
    disqusShortname = "songru"
    fuck = "fuck"
[[menu.main]]	# posts
    name = "Posts"
    url = "/posts"
[[menu.main]]	# tags
    name = "Categories"
    url = "/categories"
[[menu.main]]	# tags
    name = "Tags"
    url = "/tags"
[[menu.social]]	#社交网落链接,icon
    pre = "<i class='fa fa-github' style='font-size:22px;'></i>"
    url = "https://github.com/underspirit"
    identifier = "weibo"
 
 #[[menu.footer]]	#底部链接
 #   name = "Blog"
 #   url = "/posts"
